### PR TITLE
Added commands for WSL, updated Python version and added SQLite VS Co…

### PR DESCRIPTION
**Pull request by jisie**
…de extension

### CODE REVIEW

**Comment by JoeShep** [comment]
Not seeing WSL commands. Only file change is to the OSX installs chapter.

**Comment by JoeShep** [comment]
Ohh, I take it back. I see that you made a table in the OSX chapter. But, WSL is for Windows. Was your plan to consolidate back to a single install chapter? If so, should rename it

**Comment by jisie** [comment]
Yeah, that was kinda confusing because the installations are basically the same after those two commands. Ok, so I've taken out the link to the Windows installations chapter. It still exists in case we need it.

**Comment by jisie** [comment]
@JoeShep @MissPeperr

**Comment by JoeShep** [comment]
👍 :shipit:

**Pull request merged**
